import Head from 'next/head'
import CookieStandHeader from '../components/header'
import CookieStandForm from '../components/main'
import Footer from '../components/footer'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  

      <CookieStandHeader/>
      
      <CookieStandForm />
      <p>Report Table</p>
      <Footer/>
    </div>
  )
}